# Generated by Django 4.1.4 on 2022-12-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_api", "0002_alter_story_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
