# Generated by Django 4.1.4 on 2023-05-13 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_api", "0003_alter_story_image"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="story",
            table="story",
        ),
    ]
