# Generated by Django 4.1.4 on 2023-05-13 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_api", "0004_alter_story_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="query",
            table="Query",
        ),
    ]
