# Generated by Django 4.1.4 on 2023-05-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_api", "0005_alter_query_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="story",
            table="Story",
        ),
    ]
