# Generated by Django 4.1.4 on 2022-12-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Query",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("source", models.CharField(blank=True, max_length=255)),
                ("default", models.BooleanField(blank=True, null=True)),
                ("keyword", models.CharField(blank=True, max_length=255)),
                (
                    "quantity",
                    models.PositiveIntegerField(blank=True, default=10, null=True),
                ),
                ("date_from", models.CharField(blank=True, max_length=255)),
                ("date_to", models.CharField(blank=True, max_length=255)),
                ("language", models.CharField(blank=True, max_length=255)),
                ("sort_by", models.CharField(blank=True, max_length=255)),
                ("type", models.CharField(blank=True, max_length=255)),
                ("sa", models.CharField(blank=True, default="", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("headline", models.TextField()),
                ("source", models.CharField(max_length=255)),
                ("content_preview", models.TextField(blank=True)),
                ("content_full", models.TextField(blank=True)),
                ("author", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("url", models.TextField()),
                ("image", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("sub", models.TextField(blank=True)),
                ("pol", models.TextField(blank=True)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
