# Generated by Django 4.1.4 on 2022-12-17 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("newsapi", "0002_delete_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="query",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
